st.title("Metodologia da seguire")
st.write("E' un processo iterativo")
st.write("1 - Quale problema stiamo tentando di risolvere ? : 1 Problem definition")
st.write("2 - Quali dati abbiamo ? : 2 Data")
st.write("3 - Cosa definisce il successo ? : 3 Evaluation")
st.write("4 - Quali caratteristiche dobbiamo modellare ? : 4 - Features")
st.write("5 - Quale tipo di modello dovremmo utilizzare ? : 5 - Modelling")
st.write("6 - Cosa abbiamo sperimentato / cosa altro dobbiamo fare ? : 6 - Experiments")
st.write("----------------------------------------------------------------------------")
